(function(f){let h=window.WPD.ajaxsearchpro.helpers;f.fn.extend(window.WPD.ajaxsearchpro.plugin,{liveLoad:function(c,d,b,n,r){function q(l){let e=h.Hooks.applyFilters("asp/live_load/raw_data",l,a);var m=new DOMParser;let t=m.parseFromString(e,"text/html"),p=f(t);a.o.statistics&&a.stat_addKeyword(a.o.id,a.n("text").val());if(""!=e&&0<p.length&&0<p.find(g).length){e=e.replace(/&asp_force_reset_pagination=1/gmi,"");e=e.replace(/%26asp_force_reset_pagination%3D1/gmi,"");e=e.replace(/&#038;asp_force_reset_pagination=1/gmi,
"");h.isSafari()&&(e=e.replace(/srcset/gmi,"nosrcset"));e=h.Hooks.applyFilters("asp_live_load_html",e,a.o.id,a.o.iid);e=h.wp_hooks_apply_filters("asp_live_load_html",e,a.o.id,a.o.iid);p=f(m.parseFromString(e,"text/html"));m=p.find(g).get(0);m=h.Hooks.applyFilters("asp/live_load/replacement_node",m,a,k.get(0),e);null!=m&&k.get(0).parentNode.replaceChild(m,k.get(0));k=f(g).first();b&&(document.title=t.title,history.pushState({},null,d));f(g).first().find(".woocommerce-ordering select.orderby").on("change",
function(){f(this).closest("form").trigger("submit")});if(1==a.o.singleHighlight)f(g).find("a").on("click",function(){localStorage.removeItem("asp_phrase_highlight");""!=h.unqoutePhrase(a.n("text").val())&&localStorage.setItem("asp_phrase_highlight",JSON.stringify({phrase:h.unqoutePhrase(a.n("text").val()),id:a.o.id}))});h.Hooks.applyFilters("asp/live_load/finished",d,a,g,k.get(0));ASP.initialize();a.lastSuccesfulSearch=f("form",a.n("searchsettings")).serialize()+a.n("text").val().trim();a.lastSearchData=
e;a.setLiveLoadCache(l,c)}a.n("s").trigger("asp_search_end",[a.o.id,a.o.iid,a.n("text").val(),e],!0,!0);let u,v;null==(v=(u=a).gaEvent)||v.call(u,"search_end",{results_count:"unknown"});let w,x;null==(x=(w=a).gaPageview)||x.call(w,a.n("text").val());a.hideLoader();k.css("opacity",1);a.searching=!1;""!=a.n("text").val()&&a.n("proclose").css({display:"block"})}let g=c;if("body"==g||"html"==g)return console.log("Ajax Search Pro: Do not use html or body as the live loader selector."),!1;let a=this;""!=
ASP.pageHTML&&a.setLiveLoadCache(ASP.pageHTML,c);b="undefined"==typeof b?!0:b;n="undefined"==typeof n?!1:n;let y=".search-content #content #Content div[role=main] main[role=main] div.theme-content div.td-ss-main-content main.l-content #primary".split(" ");"#main"!=g&&y.unshift("#main");if(1>f(g).length&&(y.forEach(function(l,e){if(0<f(l).length)return g=l,!1}),1>f(g).length))return console.log("Ajax Search Pro: The live search selector does not exist on the page."),!1;g=h.Hooks.applyFilters("asp/live_load/selector",
g,this);let k=f(g).first();a.searchAbort();k.css("opacity",.4);h.Hooks.applyFilters("asp/live_load/start",d,a,g,k.get(0));n||1!=a.n("searchsettings").find("input[name=filters_initial]").val()||""!=a.n("text").val()?"undefined"!=typeof r?q(r.html):(a.searching=!0,a.post=f.fn.ajax({url:d,method:"GET",success:function(l){q(l)},dataType:"html",fail:function(l){k.css("opacity",1);l.aborted||(k.html("This request has failed. Please check your connection."),a.hideLoader(),a.searching=!1,a.n("proclose").css({display:"block"}))}})):
window.WPD.intervalUntilExecute(function(){q(ASP.pageHTML)},function(){return""!=ASP.pageHTML})},getCurrentLiveURL:function(){var c="asp_ls="+h.nicePhrase(this.n("text").val());let d="&",b=window.location.href;b=-1<b.indexOf("asp_ls=")?b.slice(0,b.indexOf("asp_ls=")):b;b=-1<b.indexOf("asp_ls&")?b.slice(0,b.indexOf("asp_ls&")):b;b=-1<b.indexOf("p_asid=")?b.slice(0,b.indexOf("p_asid=")):b;b=-1<b.indexOf("asp_")?b.slice(0,b.indexOf("asp_")):b;-1===b.indexOf("?")&&(d="?");c=b+d+c+"&asp_active=1&asp_force_reset_pagination=1&p_asid="+
this.o.id+"&p_asp_data=1&"+f("form",this.n("searchsettings")).serialize();return c=c.replace("?&","?")},initLiveLoaderPopState:function(){let c=this;c.liveLoadCache=[];window.addEventListener("popstate",d=>{d=c.getLiveLoadCache();!1!==d&&(c.n("text").val(d.phrase),h.formData(f("form",c.n("searchsettings")),d.settings),c.resetNoUISliderFilters(),c.liveLoad(d.selector,document.location.href,!1,!1,d))});""==ASP.pageHTML&&"undefined"===typeof ASP._ajax_page_html&&(ASP._ajax_page_html=!0,f.fn.ajax({url:c.currentPageURL,
method:"GET",success:function(d){ASP.pageHTML=d},dataType:"html"}))},setLiveLoadCache:function(c,d){0==this.liveLoadCache.filter(b=>b.href==document.location.href).length&&this.liveLoadCache.push({href:c==ASP.pageHTML?this.currentPageURL:document.location.href,phrase:c==ASP.pageHTML?"":this.n("text").val(),selector:d,html:c,settings:c==ASP.pageHTML?this.originalFormData:h.formData(f("form",this.n("searchsettings")))})},getLiveLoadCache:function(){let c=this.liveLoadCache.filter(d=>d.href==document.location.href);
return 0<c.length?c[0]:!1}})})(WPD.dom);
